--디비 만들기
create databases gymkkong;

CREATE TABLE member(id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE, phone_num VARCHAR(255),age VARCHAR(255),gender ENUM('m','f'), grade ENUM('BRONZE','GOLD','DIAMOND'), status ENUM('Y', 'N'), NOT NULL);
CREATE TABLE place(id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL, address VARCHAR(255) NOT NULL);
CREATE TABLE trainer(id BIGINT AUTO_INCREMENT PRIMARY KEY, name VARCHAR(255) NOT NULL, email VARCHAR(255) NOT NULL UNIQUE, phone_num VARCHAR(255));
CREATE TABLE room(id BIGINT AUTO_INCREMENT PRIMARY KEY,place_id BIGINT NOT NULL,room_num INT NOT NULL, FOREIGN KEY(place_id) REFERENCES place(id));
CREATE TABLE class(id BIGINT AUTO_INCREMENT PRIMARY KEY,trainer_id BIGINT NOT NULL,room_id BIGINT NOT NULL, class_name VARCHAR(255) NOT NULL, start_time DATETIME NOT NULL, capacity INT NOT NULL, FOREIGN KEY(trainer_id) REFERENCES trainer(id), FOREIGN KEY (room_id) REFERENCES room(id));
CREATE TABLE attendance(id BIGINT AUTO_INCREMENT PRIMARY KEY, class_id BIGINT NOT NULL, member_id BIGINT NOT NULL,status ENUM('Y','N') DEFAULT 'N', FOREIGN KEY(class_id) REFERENCES class(id), FOREIGN KEY (member_id) REFERENCES member(id));
CREATE TABLE membership_option(id BIGINT AUTO_INCREMENT PRIMARY KEY, class_id BIGINT NOT NULL, place_id BIGINT NOT NULL,count INT NOT NULL, price INT NOT NULL, FOREIGN KEY(place_id) REFERENCES place(id));
CREATE TABLE membership(id BIGINT AUTO_INCREMENT PRIMARY KEY, membership_option_id INT NOT NULL, member_id BIGINT NOT NULL, refund_YN ENUM('Y','N') DEFAULT 'N',remain_count INT NOT NULL, FOREIGN KEY (membership_option_id) REFERENCES membership_option(id), FOREIGN KEY (member_id) REFERENCES member(id));

